name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test application (if tests exist)
        run: |
          pytest || echo "No tests found"

      - name: Run FastAPI server (demo)
        run: |
          nohup uvicorn main:app --host 0.0.0.0 --port 8000 > server.log 2>&1 &
          sleep 5
          curl -v http://127.0.0.1:8000/
