name: Build & Push Docker Image + Save Artifact

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4
      # 2. Zip source code artifact
      - name: Zip source code
        run: zip -r source_code.zip .
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      - name: Upload to Google Drive
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          COMMIT_HASH=${GITHUB_SHA::7}
          rclone copy source_code.zip gdrive:/github-artifacts/manga-server/source_code_${TIMESTAMP}_${COMMIT_HASH}.zip --progress
      # 4. Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      # 5. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # 6. Build and push image to Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: kuladracymoonlight/manga-server:latest
