name: Build & Push Docker Image + Save Artifact

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Tạo file env (nếu bạn muốn embed secret vào artifact)
      - name: Create .env file
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> .env
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env
          # thêm các biến môi trường cần thiết khác ở đây

      # 3. Zip source code + env
      - name: Zip source + env
        run: zip -r source_with_env.zip . -x "*.git*"

      # 4. Upload artifact lên Google Drive
      - name: Install rclone
        run: curl https://rclone.org/install.sh | sudo bash
      - name: Upload to Google Drive
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          COMMIT_HASH=${GITHUB_SHA::7}
          rclone copy source_with_env.zip gdrive:/github-artifacts/manga-server/source_${TIMESTAMP}_${COMMIT_HASH}.zip --progress

      # 5. Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 7. Build & push image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kuladracymoonlight/manga-server:latest
