name: Build & Push Docker Image + Artifact Backup

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. Build & Push image lên Docker Hub
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/manga-server:latest

      # 5. Build thêm bản để tạo file .tar artifact
      - name: Build image tar
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/manga-server:latest
          outputs: type=docker,dest=./manga-server-image.tar

      # 6. Cài rclone
      - name: Install rclone
        run: |
          curl https://rclone.org/install.sh | sudo bash

      # 7. Chia nhỏ file tar
      - name: Split image tar
        run: |
          split -b 1500M manga-server-image.tar manga_image_part_
          ls -lh

      # 8. Upload artifact lên Google Drive
      - name: Upload to Google Drive
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        run: |
          mkdir -p ~/.config/rclone
          echo "$RCLONE_CONF" > ~/.config/rclone/rclone.conf
          TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
          for f in manga_image_part_*; do
            rclone copy "$f" gdrive:/github-artifacts/manga-server/$TIMESTAMP/ --progress
          done
